version: '3.1'

services:
  app:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8800"
    volumes:
      - .:/app
    ports:
      - 8800:8800
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres:latest
    volumes:
      - ./data/db:/var/lib/postgresql/data
    restart: always
    env_file:
      - .env
  redis:
    container_name: redis
    image: redis:alpine
    restart: unless-stopped
  celery:
    build: .
    restart: always
    command: celery -A notification_service worker -l info
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - app
      - db

